import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ConnectButton from '../components/connect'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ConnectButton />
    </div>
  )
}

export default Home
